---
title: "Project Proposal"
author: "Seokjun Choi and Sho Kawano"
date: "`r Sys.Date()`"
output:
  revealjs::revealjs_presentation: 
    theme: serif
    incremental: false
    reveal_options:
      slideNumber: T
---

```{r include=FALSE}
library(tidyverse)
# library(gridExtra)
data <- read.csv("MH_survey_only_higher_index.csv",
    na.strings = "NA")
names(data)
names(data)[1] <- "gender"

data <- data[, -c(17:22)]


# Assigning factors 
data$gender <- factor(data$gender)
data$age_group <- factor(data$age_group)
data$country_lockdown <- factor(data$country_lockdown)
data$marital <- factor(data$marital)
data$smoking <- factor(data$smoking)
data$fivfruitveg <- factor(data$fivfruitveg)
data$shielded <- factor(data$shielded)
data$week_soc_distancing <- factor(data$week_soc_distancing)
data$athlete <- factor(data$athlete)
```


# Changed Dataset

* Similar but different research questions
* Examine how athletes & non-athletes were affected by COVID-19.
* Online Survey Data Collected as the UK + Ireland emerged from COVID-19 Lockdowns 
  + Taken 14-16 weeks after lockdowns. June/July 2020. 
  + n=753 (# of complete cases: 457)


# Data Description: Factors

* Gender (Binary). <small>Male/Female</small>
* Shielded (Quarantined). <small>Yes/No </small>
* Athlete/Non-Athlete
* Marital Status  <small>5-level </small>
* Age group <small>7-level & ordered. </small>
* Country during lockdown. <small>7-level.</small>
* Smoking status. <small>7-level.</small>
* Week Social Distancing. <small>7-level & ordered.</small>
* \# in Lockdown bubble. <small>7-level & ordered.</small>



# Data Description: Numeric

* Hours Sleep.  <small>Range: 1.5-10.5 hours</small>
* Athlete Identification Index (AIMS). <small>Range: 1-7.</small>
* Hospital Anxiety & Depression Scale (HADS). <small>Range: 0-36.</small>
* Brief Resilience Scale  (RES). <small>Range: 6-30</small>
* Loneliness Scale (LONE) <small>Range: 0-6</small>
* *Response:* MHC-SF. Represents overall well-being. <small>Range: 2-70</small>



# Main Research Questions 

* Were athletes and non-athletes affected from COVID-19 lockdown/social distancing in the same way?
* Are there sex-based differences in the effects of COVID-19 on mental health?
* Under controlled demographic information, what is the relationship between MH-SF index and other sub-indices in this survey?
* Are there additional variables having strong relationship with MH-SF index?


