---
title: "EDA Notebook"
author: "Sho"
date: "11/21/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Loading In Data

```{r cars}
data <- read.csv("MH_survey_only_higher_index.csv",
    na.strings = "NA")
names(data)

data <- data[, -c(17:22)]


# Assigning factors 
data$gender <- factor(data$gender)
data$age_group <- factor(data$age_group)
data$country_lockdown <- factor(data$country_lockdown)
data$marital <- factor(data$marital)
data$smoking <- factor(data$smoking)
data$fivfruitveg <- factor(data$fivfruitveg)
data$shielded <- factor(data$shielded)
data$week_soc_distancing <- factor(data$week_soc_distancing)
data$athlete <- factor(data$athlete)
```

# Pairs Plot

```{r}
plot(MHC_SF_OVERALL ~ gender, data = data)
plot(MHC_SF_OVERALL ~ age_group, data = data)
plot(MHC_SF_OVERALL ~ country_lockdown, data = data)
plot(MHC_SF_OVERALL ~ marital, data = data)
plot(MHC_SF_OVERALL ~ smoking, data = data)
plot(MHC_SF_OVERALL ~ fivfruitveg, data = data)
plot(MHC_SF_OVERALL ~ hour_sleep, data = data)
plot(MHC_SF_OVERALL ~ week_soc_distancing, data = data)
plot(MHC_SF_OVERALL ~ shielded, data = data)
plot(MHC_SF_OVERALL ~ lockdown_bubble, data = data)
plot(MHC_SF_OVERALL ~ athlete, data = data)
plot(MHC_SF_OVERALL ~ jitter(AIMS_TOTAL), data = data)
abline(line(data$AIMS_TOTAL, data$MHC_SF_OVERALL))
plot(MHC_SF_OVERALL ~ HADS_OVERALL, data = data)
plot(MHC_SF_OVERALL ~ RES_TOTAL, data = data)
plot(MHC_SF_OVERALL ~ LONE_TOTAL, data = data)
plot(MHC_SF_OVERALL ~ lockdown_bubble, data = data)
```


```{r}
data %>% select(gender, athlete) %>% table()
```


```{r}
data %>% select(age_group, athlete) %>% table()
```


```{r}
data %>% select(shielded, athlete) %>% table()
```


```{r}
data %>% select(marital, athlete) %>% table()
```


```{r}
data %>% select(fivfruitveg, athlete) %>% table()
```

```{r}
data %>% select(smoking, athlete) %>% table()
```


```{r}
data %>% ggplot(aes(x=gender, y=MHC_SF_OVERALL, color=athlete)) + geom_boxplot()
```



# Step-wise Regression 

```{r}
model_full <- lm(MHC_SF_OVERALL ~ ., data = data)
summary(model_full)

try(step(model_full, direction = "backward"))

model_step <- lm(MHC_SF_OVERALL ~ gender + age_group + country_lockdown + marital +
    smoking + fivfruitveg + shielded + week_soc_distancing +
    athlete + AIMS_TOTAL + HADS_OVERALL + RES_TOTAL + LONE_TOTAL, data = data)
summary(model_step)

par(mfrow = c(2, 2))
plot(model_step)



model_step2 <- lm(MHC_SF_OVERALL ~ gender + age_group + marital +
    smoking + fivfruitveg + shielded + week_soc_distancing +
    athlete + AIMS_TOTAL + HADS_OVERALL + RES_TOTAL + LONE_TOTAL, data = data)
summary(model_step2)


model_step3 <- lm(MHC_SF_OVERALL ~ gender + age_group + 
    fivfruitveg + shielded + hour_sleep +
    athlete + AIMS_TOTAL + RES_TOTAL + LONE_TOTAL + athlete, data = data) #HADS_OVERALL
summary(model_step3) #<<<<<<
par(mfrow = c(2, 2))
plot(model_step3)
```
# Collinearity 

```{r}
library(corrplot)
library(RColorBrewer)

cor_tbl = data %>% select(-MHC_SF_OVERALL) %>%  
    mutate_each(as.numeric)  %>% na.omit() %>% cor()

corrplot(cor_tbl, type="upper", order="hclust", method="color")
```

```{r}
library(corrplot)
library(RColorBrewer)

cor_tbl = data %>% select(-MHC_SF_OVERALL) %>%  
    mutate_each(as.numeric)  %>% na.omit() %>% cor()

corrplot(cor_tbl, type="upper", order="hclust", method="color",
         col=brewer.pal(n=8, name="RdYlBu"))
```


# Final Model?

```{r}
model_step4 <- lm(MHC_SF_OVERALL ~ gender + age_group + fivfruitveg + shielded  +
    athlete + AIMS_TOTAL + RES_TOTAL + LONE_TOTAL + athlete, data = data)
summary(model_step4)
```


```{r}
plot(model_step4)
```
