---
title: "LASSO"
author: "Sho"
date: "11/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


```{r cars}
# ?read.csv
data <- read.csv("MH_survey_only_higher_index.csv",
    na.strings = "NA")

names(data)
names(data)[1] <- "gender"
names(data)

data$gender <- factor(data$gender)
data$age_group <- factor(data$age_group)
data$country_lockdown <- factor(data$country_lockdown)
data$marital <- factor(data$marital)
data$smoking <- factor(data$smoking)
data$fivfruitveg <- factor(data$fivfruitveg)
data$shielded <- factor(data$shielded)
data$week_soc_distancing <- factor(data$week_soc_distancing)
data$athlete <- factor(data$athlete)

summary(data)
```


```{r}
library(gglasso)
?gglasso

model_full <- lm(MHC_SF_OVERALL ~ ., data = data )
design_matrix <- model.matrix(model_full)[,-1]
response <- model_full$model$MHC_SF_OVERALL
scaled_design_matrix <- scale(design_matrix)
scaled_response <-scale(response)

design_mat_col_group <- c(1,2,2,2,2,2,2,3,3,3,3,3,4,4,4,4,5,5,5,5,5,5,6,7,8,9,9,9,9,9,9,9,10,11,12,13,14,15)
data.frame(colnames(design_matrix), design_mat_col_group) #for check

model_full_lasso_fit <- gglasso(
    scaled_design_matrix, scaled_response,
    lambda = 0.03,
    group = design_mat_col_group, loss = "ls")
coef(model_full_lasso_fit)
plot(model_full_lasso_fit)
```

```{r}
# group lasso
gr_cv = cv.gglasso(x=scaled_design_matrix, y=scaled_response, group= design_mat_col_group, 
            loss="ls", pred.loss="L2", 
            intercept = F, nfolds=10)
c(gr_cv$lambda.min, gr_cv$lambda.1se) 
```


```{r}
plot(gr_cv)
```


